#!/bin/bash

echo "🔍 Port.ioで必要なブループリントを確認します..."
echo ""
echo "以下のURLでブループリントを確認してください:"
echo "  https://app.port.io/builder/blueprints"
echo ""
echo "必要なブループリント:"
echo "  ✅ k8s_cluster"
echo "  ✅ k8s_namespace"
echo "  ❓ k8s_workload"
echo "  ❓ k8s_replicaSet"
echo "  ❓ k8s_pod"
echo "  ❓ k8s_node"
echo ""
echo "不足しているブループリントがある場合:"
echo "  1. 「+ Blueprint」をクリック"
echo "  2. 上記のブループリントを作成"
echo "  3. 各ブループリント間のリレーションを設定"
echo ""
echo "詳細な手順は docs/portio-blueprints-setup.md を参照してください"
echo ""
